Repository slovensko-digital/avm-app-flutter, pull requests merged in 2024-11, with the labels that each got.

#70 Feature/accessibility fixes
  android/app/build.gradle
  devtools_options.yaml
  lib/bloc/present_signed_document_cubit.dart
  lib/bloc/present_signed_document_state.dart
  lib/di.config.dart
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_sk.dart
  lib/l10n/app_sk.arb
  lib/ui/screens/about_screen.dart
  lib/ui/screens/main_menu_screen.dart
  lib/ui/screens/main_screen.dart
  lib/ui/screens/present_signed_document_screen.dart
  lib/ui/screens/preview_document_screen.dart
  lib/ui/screens/qr_code_scanner_screen.dart
  lib/ui/screens/settings_screen.dart
  lib/ui/widgets/option_picker.dart
  lib/ui/widgets/signature_type_picker.dart
Labels: hackdays, accessibility

#72 Document Validation flow
  CHANGELOG.md
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
  lib/bloc/document_validation_cubit.dart
  lib/bloc/document_validation_state.dart
  lib/bloc/present_signed_document_cubit.dart
  lib/bloc/present_signed_document_state.dart
  lib/bloc/preview_document_cubit.dart
  lib/di.config.dart
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_sk.dart
  lib/l10n/app_sk.arb
  lib/oids.dart
  lib/ui/fragment/document_validation_fragment.dart
  lib/ui/fragment/document_validation_info_fragment.dart
  lib/ui/fragment/preview_document_fragment.dart
  lib/ui/screens/certificate_details_dialog.dart
  lib/ui/screens/main_screen.dart
  lib/ui/screens/preview_document_screen.dart
  lib/ui/screens/settings_screen.dart
  lib/ui/widgets/certificate_details.dart
  lib/ui/widgets/certificate_picker_item.dart
  lib/ui/widgets/chip.dart
  lib/ui/widgets/dialogs.dart
  lib/ui/widgets/document_signature_info.dart
  lib/ui/widgets/document_validation_strip.dart
  lib/ui/widgets/loading_indicator.dart
  lib/ui/widgets/markdown_text.dart
  lib/widgetbook_app.directories.g.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, hackdays

#37 Dependencies ako Git reference
  .github/workflows/android_package.yaml
  pubspec.lock
  pubspec.yaml
Labels: enhancement
